version: 2
services:
    nuki:
        image: giejay/nuki-bridge
        environment:
          - PYTHONUNBUFFERED=true
        volumes:
          - ./nuki.cfg:/opt/nuki/nuki.cfg
        privileged: true
        network_mode: host